language: r
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  cleanup: false
  on:
    branch: 
      - dev
      - master

    
branches:
  except:
  - gh-pages
