// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_lapjv
IntegerVector cpp_lapjv(NumericMatrix cost, bool maximize);
RcppExport SEXP _iGraphMatch_cpp_lapjv(SEXP costSEXP, SEXP maximizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cost(costSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lapjv(cost, maximize));
    return rcpp_result_gen;
END_RCPP
}
// cpp_lapmod
IntegerVector cpp_lapmod(int n, NumericVector cc, IntegerVector ii, IntegerVector kk, bool maximize);
RcppExport SEXP _iGraphMatch_cpp_lapmod(SEXP nSEXP, SEXP ccSEXP, SEXP iiSEXP, SEXP kkSEXP, SEXP maximizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cc(ccSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ii(iiSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type kk(kkSEXP);
    Rcpp::traits::input_parameter< bool >::type maximize(maximizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_lapmod(n, cc, ii, kk, maximize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_iGraphMatch_cpp_lapjv", (DL_FUNC) &_iGraphMatch_cpp_lapjv, 2},
    {"_iGraphMatch_cpp_lapmod", (DL_FUNC) &_iGraphMatch_cpp_lapmod, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_iGraphMatch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
